discourse_solved:
  solved_enabled:
    default: true
    client: true
  allow_solved_on_all_topics:
    default: false
    client: true
  accept_all_solutions_trust_level:
    default: 4
    client: true
    enum: "TrustLevelSetting"
    hidden: true
  accept_all_solutions_allowed_groups:
    default: "14" # auto group trust_level_4
    type: group_list
    client: false
    allow_any: false
    refresh: true
    validator: "AtLeastOneGroupValidator"
  empty_box_on_unsolved:
    default: false
    client: true
  solved_quote_length:
    default: 300
    client: false
  solved_topics_auto_close_hours:
    default: 0
    min: 0
    max: 175200 # 20 years
  show_filter_by_solved_status:
    default: false
    client: true
  notify_on_staff_accept_solved:
    default: false
  prevent_assign_notification:
    default: false
  assign_to_status_on_solved:
    default: false
  status_to_assign_on_solved:
    type: string
    default: "Done"
  disable_solved_education_message:
    default: false
  accept_solutions_topic_author:
    default: true
  solved_add_schema_markup:
    type: enum
    default: "always"
    choices:
      - "never"
      - "always"
      - "answered only"
  prioritize_solved_topics_in_search: false
  enable_solved_tags:
    type: tag_list
    default: ""

