plugins:
  solved_enabled:
    default: true
    client: true
  allow_solved_on_all_topics:
    default: false
    client: true
  accept_all_solutions_trust_level:
    default: 4
    client: true
  empty_box_on_unsolved:
    default: false
    client: true
  hide_posts_before_solution:
    default: false
    client: false
  hide_posts_after_solution:
    default: false
    client: false
